# -*- coding: utf-8 -*-
"""FarAway4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_iL2atoDhw6ZBdOsegX_9A06FNKKg88x
"""

import pandas as pd
import numpy as np

np.random.seed(42)

NUM_ROWS = 20000

track_types = ["Mainline", "Freight", "Branch"]
seasons = ["Summer", "Monsoon", "Winter"]

data = []

for i in range(NUM_ROWS):

    # =====================================
    # BASIC INFO
    # =====================================

    track_id = f"TRK_{i+1:05d}"

    latitude = np.random.uniform(28.40, 28.95)
    longitude = np.random.uniform(76.90, 77.60)

    track_type = np.random.choice(
        track_types,
        p=[0.5, 0.3, 0.2]
    )

    season = np.random.choice(
        seasons,
        p=[0.35, 0.35, 0.30]
    )

    # =====================================
    # WEATHER
    # =====================================

    if season == "Summer":

        rainfall = np.random.uniform(0, 5)
        temperature = np.random.uniform(30, 45)
        humidity = np.random.uniform(25, 60)

    elif season == "Monsoon":

        rainfall = np.random.uniform(5, 20)
        temperature = np.random.uniform(22, 35)
        humidity = np.random.uniform(60, 95)

    else:

        rainfall = np.random.uniform(0, 8)
        temperature = np.random.uniform(10, 25)
        humidity = np.random.uniform(35, 80)

    # =====================================
    # TRACK CHARACTERISTICS
    # =====================================

    track_age = np.random.randint(1, 40)

    historical_defects = np.random.poisson(
        2 + track_age / 12
    )

    days_since_inspection = np.random.randint(
        1,
        365
    )

    train_speed = np.random.uniform(
        40,
        110
    )

    maintenance_quality = np.random.uniform(
        0,
        1
    )

    # =====================================
    # BASE VIBRATION
    # =====================================

    base_vibration = np.random.uniform(
        0.5,
        4.5
    )

    # Older tracks vibrate more
    base_vibration += track_age * 0.04

    # Rainfall effect
    base_vibration += rainfall * 0.05

    # Poor maintenance
    base_vibration += (1 - maintenance_quality) * 1.5

    # Speed effect
    base_vibration += ((train_speed - 40)/70) * 0.8
    # Track type effect
    if track_type == "Branch":
        base_vibration += 0.6

    elif track_type == "Freight":
        base_vibration += 0.3

    # Sensor noise
    base_vibration += np.random.normal(
        0,
        0.4
    )

    base_vibration = max(
        0.2,
        base_vibration
    )

    # =====================================
    # SENSOR FEATURES
    # =====================================

    vibration_mean = base_vibration

    vibration_max = (
        vibration_mean +
        np.random.uniform(0.5, 4)
    )

    vibration_rms = (
        vibration_mean +
        np.random.uniform(-0.3, 1.5)
    )

    vibration_std = np.random.uniform(
        0.2,
        4
    )

    jerk = (
        vibration_mean * 0.25 +
        np.random.uniform(0, 1.5)
    )

    # =====================================
    # CONSENSUS LOGIC
    # =====================================

    anomaly_strength = (
        vibration_mean +
        vibration_std +
        jerk
    )

    consensus_count = int(
        np.clip(
            anomaly_strength / 3 +
            np.random.normal(0, 1),
            1,
            6
        )
    )

    # =====================================
    # RISK SCORE
    # =====================================

    risk_score = (

        vibration_mean * 2.0 +

        vibration_max * 1.2 +

        vibration_rms * 1.5 +

        vibration_std * 1.0 +

        jerk * 1.5 +

        consensus_count * 3.0 +

        historical_defects * 0.8 +

        track_age * 0.2 +

        rainfall * 0.2 +

        days_since_inspection * 0.02 +

        (1 - maintenance_quality) * 5
    )

    # Nonlinear interactions

    if rainfall > 12 and track_age > 25:
        risk_score += 5

    if consensus_count >= 4:
        risk_score += 4

    if historical_defects > 8:
        risk_score += 3

    risk_score += np.random.normal(
        0,
        4
    )

    risk_score = max(0, risk_score)

    # =====================================
    # MAINTENANCE DATA
    # =====================================

    maintenance_cost = int(
        10000 +
        risk_score * 1500 +
        np.random.normal(0, 10000)
    )

    maintenance_cost = max(
        maintenance_cost,
        10000
    )

    estimated_failure_days = int(
        np.clip(
            365 -
            risk_score * 2 +
            np.random.normal(0, 25),
            1,
            365
        )
    )

    # =====================================
    # DEFECT TYPE
    # =====================================

    defect_type = np.random.choice([
        "Normal",
        "Loose Joint",
        "Misalignment",
        "Track Wear",
        "Crack"
    ])

    data.append([

        track_id,

        round(latitude, 6),
        round(longitude, 6),

        round(vibration_mean, 2),
        round(vibration_max, 2),
        round(vibration_rms, 2),
        round(vibration_std, 2),
        round(jerk, 2),

        round(train_speed, 2),

        consensus_count,

        round(rainfall, 2),
        round(temperature, 2),
        round(humidity, 2),

        historical_defects,

        days_since_inspection,

        track_age,

        track_type,

        season,

        defect_type,

        round(risk_score, 2),

        maintenance_cost,

        estimated_failure_days
    ])

# =====================================
# DATAFRAME
# =====================================

columns = [

    "Track_ID",

    "Latitude",
    "Longitude",

    "Vibration_Mean",
    "Vibration_Max",
    "Vibration_RMS",
    "Vibration_STD",
    "Jerk",

    "Train_Speed",

    "Consensus_Count",

    "Rainfall",
    "Temperature",
    "Humidity",

    "Historical_Defects",

    "Days_Since_Last_Inspection",

    "Track_Age_Years",

    "Track_Type",

    "Season",

    "Defect_Type",

    "Risk_Score",

    "Maintenance_Cost",

    "Estimated_Failure_Days"
]

df = pd.DataFrame(
    data,
    columns=columns
)

# =====================================
# BALANCED LABEL CREATION
# =====================================

df["Risk_Label"] = pd.qcut(
    df["Risk_Score"],
    q=[0, 0.25, 0.55, 0.80, 1.0],
    labels=[
        "Safe",
        "Medium",
        "High",
        "Critical"
    ]
)

df["Risk_Label"] = df["Risk_Label"].astype(str)

# =====================================
# SAVE
# =====================================

df.to_csv(
    "track_health_dataset_v4.csv",
    index=False
)

print("Dataset Generated Successfully!")
print("Shape:", df.shape)

print("\nClass Distribution:")
print(df["Risk_Label"].value_counts())

import pandas as pd
import numpy as np

np.random.seed(42)

NUM_ROWS = 20000

track_types = [
    "Mainline",
    "Freight",
    "Branch"
]

seasons = [
    "Summer",
    "Monsoon",
    "Winter"
]


data = []


for i in range(NUM_ROWS):


    # =====================================
    # BASIC INFORMATION
    # =====================================

    track_id = f"TRK_{i+1:05d}"


    latitude = np.random.uniform(
        28.40,
        28.95
    )

    longitude = np.random.uniform(
        76.90,
        77.60
    )


    track_type = np.random.choice(
        track_types,
        p=[0.5,0.3,0.2]
    )


    season = np.random.choice(
        seasons,
        p=[0.35,0.35,0.30]
    )



    # =====================================
    # WEATHER
    # =====================================


    if season=="Summer":

        rainfall=np.random.uniform(0,5)

        temperature=np.random.uniform(
            30,
            45
        )

        humidity=np.random.uniform(
            25,
            60
        )


    elif season=="Monsoon":

        rainfall=np.random.uniform(
            5,
            25
        )

        temperature=np.random.uniform(
            22,
            35
        )

        humidity=np.random.uniform(
            60,
            95
        )


    else:

        rainfall=np.random.uniform(
            0,
            8
        )

        temperature=np.random.uniform(
            10,
            25
        )

        humidity=np.random.uniform(
            35,
            80
        )



    # =====================================
    # TRACK PARAMETERS
    # =====================================


    track_age=np.random.randint(
        1,
        50
    )


    days_since_inspection=np.random.randint(
        1,
        365
    )


    maintenance_quality=np.random.uniform(
        0,
        1
    )



    historical_defects=np.random.poisson(
        1 + track_age/8
    )


    # New parameters

    daily_train_frequency=np.random.randint(
        5,
        100
    )


    if track_type=="Freight":

        axle_load=np.random.uniform(
            20,
            35
        )

    else:

        axle_load=np.random.uniform(
            15,
            30
        )



    train_speed=np.random.uniform(
        40,
        120
    )



    # =====================================
    # VIBRATION MODEL
    # =====================================


    vibration_mean=(

        0.8

        +

        track_age*0.06

        +

        rainfall*0.06

        +

        daily_train_frequency*0.015

        +

        axle_load*0.04

        +

        (1-maintenance_quality)*2

    )


    if track_type=="Branch":

        vibration_mean+=0.5


    elif track_type=="Freight":

        vibration_mean+=0.3



    vibration_mean += np.random.normal(
        0,
        0.35
    )



    vibration_mean=max(
        0.2,
        vibration_mean
    )



    # =====================================
    # SENSOR FEATURES
    # =====================================


    vibration_std=(

        vibration_mean*0.18

        +

        track_age*0.03

        +

        np.random.normal(
            0,
            0.25
        )

    )


    vibration_std=max(
        0.1,
        vibration_std
    )



    vibration_max=(

        vibration_mean

        +

        np.random.uniform(
            1,
            5
        )

    )



    vibration_rms=(

        vibration_mean

        +

        np.random.uniform(
            -0.2,
            1
        )

    )



    jerk=(

        vibration_mean*0.3

        +

        vibration_std*0.2

        +

        np.random.uniform(
            0,
            1
        )

    )



    # =====================================
    # CONSENSUS FROM MULTIPLE TRAINS
    # =====================================


    anomaly_strength=(

        vibration_mean

        +

        vibration_std

        +

        jerk

        +

        historical_defects*0.2

    )


    consensus_count=int(
        np.clip(

            anomaly_strength/3

            +

            np.random.normal(
                0,
                0.5
            ),

            1,
            6

        )
    )



    # =====================================
    # RISK SCORE
    # =====================================


    risk_score=(

        vibration_mean*2

        +

        vibration_max*1.2

        +

        vibration_rms*1.5

        +

        vibration_std

        +

        jerk*1.5

        +

        consensus_count*3

        +

        historical_defects*1

        +

        track_age*0.3

        +

        rainfall*0.2

        +

        days_since_inspection*0.015

        +

        (1-maintenance_quality)*6

        +

        daily_train_frequency*0.1

        +

        axle_load*0.2

    )



    # Extreme conditions


    if rainfall>15 and track_age>30:

        risk_score+=8



    if consensus_count>=5:

        risk_score+=6



    if historical_defects>10:

        risk_score+=5



    risk_score += np.random.normal(
        0,
        5
    )


    risk_score=max(
        0,
        risk_score
    )



    # =====================================
    # DEFECT GENERATION
    # =====================================


    if risk_score < 35:

        defect_type="Normal"


    elif risk_score < 60:

        defect_type=np.random.choice(
            [
                "Normal",
                "Loose Joint"
            ],
            p=[
                0.6,
                0.4
            ]
        )


    elif risk_score < 90:

        defect_type=np.random.choice(
            [
                "Loose Joint",
                "Misalignment",
                "Track Wear"
            ]
        )


    else:

        defect_type=np.random.choice(
            [
                "Track Wear",
                "Crack"
            ],
            p=[
                0.4,
                0.6
            ]
        )



    # =====================================
    # MAINTENANCE OUTPUTS
    # =====================================


    maintenance_cost=int(

        10000

        +

        risk_score*1800

        +

        np.random.normal(
            0,
            8000
        )

    )


    maintenance_cost=max(
        maintenance_cost,
        10000
    )



    estimated_failure_days=int(

        np.clip(

            365

            -

            risk_score*2

            +

            np.random.normal(
                0,
                20
            ),

            1,
            365

        )

    )



    data.append([

        track_id,

        latitude,
        longitude,

        vibration_mean,
        vibration_max,
        vibration_rms,
        vibration_std,

        jerk,

        train_speed,

        consensus_count,

        rainfall,
        temperature,
        humidity,

        historical_defects,

        days_since_inspection,

        track_age,

        daily_train_frequency,

        axle_load,

        maintenance_quality,

        track_type,

        season,

        defect_type,

        risk_score,

        maintenance_cost,

        estimated_failure_days

    ])





# =====================================
# CREATE DATAFRAME
# =====================================


columns=[

"Track_ID",

"Latitude",
"Longitude",

"Vibration_Mean",
"Vibration_Max",
"Vibration_RMS",
"Vibration_STD",

"Jerk",

"Train_Speed",

"Consensus_Count",

"Rainfall",
"Temperature",
"Humidity",

"Historical_Defects",

"Days_Since_Last_Inspection",

"Track_Age_Years",

"Daily_Train_Frequency",

"Axle_Load",

"Maintenance_Quality",

"Track_Type",

"Season",

"Defect_Type",

"Risk_Score",

"Maintenance_Cost",

"Estimated_Failure_Days"

]


df=pd.DataFrame(
    data,
    columns=columns
)



# =====================================
# CREATE LABEL
# =====================================


df["Risk_Label"]=pd.qcut(

    df["Risk_Score"],

    q=[
        0,
        0.25,
        0.55,
        0.80,
        1
    ],

    labels=[

        "Safe",
        "Medium",
        "High",
        "Critical"

    ]

)



df["Risk_Label"]=df["Risk_Label"].astype(str)



# =====================================
# SAVE
# =====================================


df.to_csv(
    "track_health_dataset_v5.csv",
    index=False
)



print(
    "Dataset Generated Successfully!"
)


print(
    "Shape:",
    df.shape
)


print(
    df["Risk_Label"].value_counts()
)

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier

import matplotlib.pyplot as plt

df = pd.read_csv(
    "track_health_dataset_v5.csv"
)


print("Dataset Shape:")
print(df.shape)


print("\nFirst 5 rows:")
print(df.head())

print(
    df.isnull().sum()
)

print(
    df["Risk_Label"].value_counts()
)

df = df.drop(
    columns=[
        "Track_ID",
        "Risk_Score",
        "Maintenance_Cost",
        "Estimated_Failure_Days"
    ]
)


print(df.shape)

X = df.drop(
    columns=[
        "Risk_Label"
    ]
)


y = df["Risk_Label"]


print(X.shape)
print(y.shape)

target_encoder = LabelEncoder()


y = target_encoder.fit_transform(
    y
)


print(
    target_encoder.classes_
)

X = pd.get_dummies(
    X,
    columns=[
        "Track_Type",
        "Season",
        "Defect_Type"
    ],
    drop_first=True
)


print(X.shape)

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)


print(
    X_train.shape
)

print(
    X_test.shape
)

model = XGBClassifier(

    objective="multi:softprob",

    num_class=4,


    n_estimators=350,


    max_depth=5,


    learning_rate=0.05,


    subsample=0.85,


    colsample_bytree=0.85,


    min_child_weight=3,


    gamma=0.2,


    reg_lambda=2,


    random_state=42,


    eval_metric="mlogloss"

)

model.fit(

    X_train,

    y_train

)

y_pred = model.predict(
    X_test
)

accuracy = accuracy_score(
    y_test,
    y_pred
)


print(
    "Accuracy:",
    accuracy
)

print(

classification_report(

    y_test,

    y_pred,

    target_names=
    target_encoder.classes_

)

)

cm = confusion_matrix(
    y_test,
    y_pred
)


print(cm)