import os
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt
from datetime import datetime
import json

# Import local data loader to fetch real system state
from data_loader import load_all_data
from routers.digital_twin import get_system_state

def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)

def generate_reports():
    print("Starting Automated Fleet Analysis...")
    ensure_dir("outputs")
    
    # 1. Fetch live system data
    print("Fetching digital twin data...")
    load_all_data()
    data = get_system_state()
    rakes = data.get("rakes", [])
    alerts = [e for e in data.get("recent_events", []) if e.get("severity") in ("critical", "warning")]
    track_alerts = data.get("track_alerts", [])
    vision_alerts = data.get("vision_alerts", [])
    sustainability = data.get("sustainability", {})
    
    total_rakes = len(rakes)
    healthy_rakes = sum(1 for r in rakes if r.get('health_score', 0) >= 80)
    critical_rakes = sum(1 for r in rakes if r.get('health_score', 0) < 50)
    avg_health = sum(r.get('health_score', 0) for r in rakes) / total_rakes if total_rakes > 0 else 0
    
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    date_str = datetime.now().strftime("%Y%m%d")
    
    # 2. Generate DOCX Report
    print("Generating DOCX Executive Summary...")
    doc = Document()
    
    # Title
    title = doc.add_heading('RailGuard AI: Fleet Executive Summary', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph(f"Generated by RailGuard AI Agent on {now_str}")
    
    doc.add_heading('1. Fleet Overview', level=1)
    doc.add_paragraph(f"The network currently has {total_rakes} active rakes in transit or stationary.")
    doc.add_paragraph(f"Average Fleet Health: {avg_health:.1f}%")
    
    p = doc.add_paragraph()
    p.add_run('Healthy Rakes (Health >= 80%): ').bold = True
    p.add_run(str(healthy_rakes))
    
    p = doc.add_paragraph()
    p.add_run('Critical Rakes (Health < 50%): ').bold = True
    p.add_run(str(critical_rakes))
    
    doc.add_heading('2. Active Alerts', level=1)
    if not alerts:
        doc.add_paragraph("No critical or warning alerts active at this time.")
    else:
        for alert in alerts[:10]: # Max 10 in report
            doc.add_paragraph(
                f"[{alert.get('severity', 'UNKNOWN').upper()}] {alert.get('message', '')} "
                f"(Location: {alert.get('location', 'N/A')}, Time: {alert.get('timestamp', 'N/A')})",
                style='List Bullet'
            )
            
    doc.add_heading('3. Track Health Analysis', level=1)
    doc.add_paragraph(f"High-Risk Track Segments Detected: {len(track_alerts)}")
    if track_alerts:
        for ta in track_alerts[:5]:
            doc.add_paragraph(f"Segment {ta.get('segment_id', 'Unknown')} ({ta.get('source', '')} -> {ta.get('destination', '')}) - Risk Score: {ta.get('risk_score', 0)}", style='List Bullet')

    doc.add_heading('4. Forward Vision Safety', level=1)
    doc.add_paragraph(f"Active Camera Vision Alerts: {len(vision_alerts)}")
    if vision_alerts:
        for va in vision_alerts[:5]:
            doc.add_paragraph(f"[{va.get('risk_level', 'HIGH')}] {va.get('object_detected', 'Obstacle')} detected at {va.get('distance_m', 0)}m on Rake {va.get('rake_id', 'N/A')}", style='List Bullet')

    doc.add_heading('5. Sustainability Impact', level=1)
    doc.add_paragraph(f"CO2 Saved: {sustainability.get('co2_saved_tons', 0)} Tons")
    doc.add_paragraph(f"Empty KM Avoided: {sustainability.get('empty_km_avoided', 0)} KM")
    doc.add_paragraph(f"Revenue Saved: ₹{sustainability.get('revenue_saved_cr', 0)} Cr")
            
    doc.add_heading('6. Automated Recommendations', level=1)
    doc.add_paragraph(
        "Based on the current predictive maintenance model, rakes with health below 50% "
        "should be scheduled for immediate triage at the next available junction. "
        "AI Reallocation models suggest re-routing excess freight to healthy adjacent lines."
    )
    
    docx_path = f"outputs/Fleet_Analysis_Report_{date_str}.docx"
    doc.save(docx_path)
    print(f"Saved: {docx_path}")
    
    # 3. Generate PPTX Presentation
    print("Generating PPTX Presentation...")
    prs = Presentation()
    
    # Slide 1: Title
    slide_layout = prs.slide_layouts[0] # Title slide
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "RailGuard AI: Daily Fleet Status"
    subtitle.text = f"Automated Generation\n{now_str}"
    
    # Slide 2: High Level Metrics
    slide_layout = prs.slide_layouts[1] # Title and Content
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "Fleet Health & Metrics"
    
    body_shape = slide.shapes.placeholders[1]
    tf = body_shape.text_frame
    tf.text = f"Total Monitored Rakes: {total_rakes}"
    
    p = tf.add_paragraph()
    p.text = f"Average System Health: {avg_health:.1f}%"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"Healthy Units (>80%): {healthy_rakes}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"Critical Units (<50%): {critical_rakes}"
    p.level = 1
    
    # Slide 3: Critical Action Items
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "Critical Action Items"
    tf = slide.shapes.placeholders[1].text_frame
    
    if critical_rakes > 0:
        tf.text = "Immediate Maintenance Required:"
        for r in [r for r in rakes if r.get('health_score', 0) < 50][:5]:
            p = tf.add_paragraph()
            p.text = f"{r.get('rake_id')} ({r.get('rake_type')}): {r.get('health_score')}% Health"
            p.level = 1
    else:
        tf.text = "No immediate critical maintenance required."
        
    # Slide 4: Extended Telemetry (Track, Vision, Sustainability)
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "System Telemetry & Sustainability"
    tf = slide.shapes.placeholders[1].text_frame
    
    tf.text = "Infrastructure & Safety:"
    
    p = tf.add_paragraph()
    p.text = f"High-Risk Track Segments: {len(track_alerts)}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"Forward Vision Camera Alerts: {len(vision_alerts)}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Sustainability Impact:"
    p.level = 0
    
    p = tf.add_paragraph()
    p.text = f"CO2 Saved: {sustainability.get('co2_saved_tons', 0)} Tons"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"Empty KM Avoided: {sustainability.get('empty_km_avoided', 0)} KM"
    p.level = 1
        
    pptx_path = f"outputs/Fleet_Presentation_{date_str}.pptx"
    prs.save(pptx_path)
    print(f"Saved: {pptx_path}")
    
    print("Automated Analysis Complete.")

if __name__ == "__main__":
    generate_reports()
